In [81]:
import numpy as np
import pandas as pd

In [82]:
data = pd.read_csv('C:/Users/DELL/Desktop/veri bilimi kampı/heart.csv')
df = data.copy()
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [84]:
df.describe().T

count        mean        std    min    25%    50%    75%    max
age       1025.0   54.434146   9.072290   29.0   48.0   56.0   61.0   77.0
sex       1025.0    0.695610   0.460373    0.0    0.0    1.0    1.0    1.0
cp        1025.0    0.942439   1.029641    0.0    0.0    1.0    2.0    3.0
trestbps  1025.0  131.611707  17.516718   94.0  120.0  130.0  140.0  200.0
chol      1025.0  246.000000  51.592510  126.0  211.0  240.0  275.0  564.0
fbs       1025.0    0.149268   0.356527    0.0    0.0    0.0    0.0    1.0
restecg   1025.0    0.529756   0.527878    0.0    0.0    1.0    1.0    2.0
thalach   1025.0  149.114146  23.005724   71.0  132.0  152.0  166.0  202.0
exang     1025.0    0.336585   0.472772    0.0    0.0    0.0    1.0    1.0
oldpeak   1025.0    1.071512   1.175053    0.0    0.0    0.8    1.8    6.2
slope     1025.0    1.385366   0.617755    0.0    1.0    1.0    2.0    2.0
ca        1025.0    0.754146   1.030798    0.0    0.0    0.0    1.0    4.0
thal      1025.0    2.323902   0.620660    0.0    2.0    2.0    3.0    3.0
target    1025.0    0.513171   0.500070    0.0    0.0    1.0    1.0    1.0

In [85]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [86]:
df.age, labels=pd.factorize(df['age'])

In [87]:
from sklearn.neighbors import LocalOutlierFactor

In [88]:
labels

Index([52, 53, 70, 61, 62, 58, 55, 46, 54, 71, 43, 34, 51, 50, 60, 67, 45, 63,
       42, 44, 56, 57, 59, 64, 65, 41, 66, 38, 49, 48, 29, 37, 47, 68, 76, 40,
       39, 77, 69, 35, 74],
      dtype='int64')

In [89]:
lof = LocalOutlierFactor(n_neighbors = 20)

In [90]:
lof

LocalOutlierFactor()

In [91]:
scores = lof.fit_predict(df)
scores

array([1, 1, 1, ..., 1, 1, 1])

In [92]:
np.where(scores == -1)[0]

array([ 101,  149,  151,  158,  192,  216,  246,  267,  296,  326,  336,
        356,  378,  464,  475,  478,  487,  559,  587,  682,  733,  871,
        916,  930,  964, 1014], dtype=int64)

In [93]:
df.drop(np.where(scores == -1)[0], axis=0, inplace=True)

In [94]:
data.age.value_counts()

age
58    68
57    57
54    53
59    46
52    43
51    39
56    39
62    37
60    37
44    36
64    34
41    32
63    32
67    31
61    31
55    30
65    27
43    26
42    26
53    26
66    25
45    25
48    23
46    23
50    21
47    18
49    17
35    15
39    14
70    14
68    12
38    12
71    11
40    11
69     9
37     6
34     6
29     4
76     3
77     3
74     3
Name: count, dtype: int64

In [49]:
from sklearn.feature_selection import SelectKBest,f_classif

x=df.drop("age",axis=1)
y=df["age"]

cls = SelectKBest(score_func=f_classif,k=4)
cls.fit(x,y)

SelectKBest(k=4)

In [50]:
X = df.drop('age',axis=1)
y = df['age']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [51]:
cls.fit(x,y)

SelectKBest(k=4)

In [52]:
cls.scores_

array([4.52221947, 4.52352024, 6.10829258, 4.22369529, 3.98906323,
       5.16328774, 9.00023213, 4.79287142, 5.39217205, 4.20106323,
       7.78802669, 3.19431782, 5.16528938])

In [53]:
cls.get_support(indices=True)

array([ 2,  6,  8, 10], dtype=int64)

In [54]:
X.columns[cls.get_support(indices=True)]

Index(['trestbps', 'thalach', 'oldpeak', 'ca'], dtype='object')

In [55]:
X.columns

Index(['sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang',
       'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [56]:
X.drop(['sex', 'cp', 'chol', 'fbs', 'restecg', 'exang', 'slope', 'thal', 'target'], axis=1, inplace=True)

In [57]:
X.describe().T

count        mean        std   min    25%    50%    75%    max
trestbps  999.0  131.406406  17.214869  94.0  120.0  130.0  140.0  200.0
thalach   999.0  149.274274  22.190983  88.0  133.0  152.0  165.0  202.0
oldpeak   999.0    1.073974   1.180683   0.0    0.0    0.8    1.8    6.2
ca        999.0    0.757758   1.038043   0.0    0.0    0.0    1.0    4.0

In [59]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [60]:
X = scale.fit_transform(X.values)
X

array([[-0.37233018,  0.84426656, -0.06268495,  1.19731546],
       [ 0.49944604,  0.25814961,  1.71683809, -0.73035278],
       [ 0.79003811, -1.09442798,  1.29314213, -0.73035278],
       ...,
       [-1.24410641, -1.41002941, -0.06268495,  0.23348134],
       [-1.24410641,  0.43849329, -0.91007687, -0.73035278],
       [-0.66292226, -1.63545901,  0.27627182,  0.23348134]])

In [62]:
x = pd.DataFrame(X)
x

0         1         2         3
0   -0.372330  0.844267 -0.062685  1.197315
1    0.499446  0.258150  1.716838 -0.730353
2    0.790038 -1.094428  1.293142 -0.730353
3    0.964393  0.528665 -0.910077  0.233481
4    0.383209 -1.951060  0.699968  2.161150
..        ...       ...       ...       ...
994  0.499446  0.663923 -0.910077 -0.730353
995 -0.372330 -0.373053  1.462621  0.233481
996 -1.244106 -1.410029 -0.062685  0.233481
997 -1.244106  0.438493 -0.910077 -0.730353
998 -0.662922 -1.635459  0.276272  0.233481

[999 rows x 4 columns]

In [63]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
models ={'RF': RandomForestClassifier(), 'GB':GradientBoostingClassifier(), 'svc':SVC(), 'XGB':xgb.XGBClassifier()}

In [64]:
for modelName, model in models.items():
    model.fit(X_train, y_train)
    accuracy= accuracy_score(y_test, model.predict(X_test))
    print(f"model: {modelName}, 'accuracy':{accuracy}")

model: RF, 'accuracy':0.985
model: GB, 'accuracy':0.97
model: svc, 'accuracy':0.05
model: XGB, 'accuracy':0.97


In [65]:
svm = SVC()
param_grid = {'C': [0.1, 1, 10, 100, 1000],
             'gamma':[1, 0.1, 0.01, 0.001, 0.0001],
             'kernel':['rbf']}

grid = GridSearchCV(svm, cv=5, param_grid = param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.075 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.075 total time=   0.0s


C:\Users\DELL\PycharmProjects\pythonProject1\.venv\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.075 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.069 total time=   0.2s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.069 total time=   0.2s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.075 total time=   0.2s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.075 total time=   0.1s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.075 total time=   0.2s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.069 total time=   0.2s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.069 total time=   0.2s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.075 total time=   0.2s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.075 total time=   0.2s
[CV 3/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.075 total time=   0.2s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.069 total time=   0.1s
[CV 5/5] END .....C=0.1, gam

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [66]:
grid.score(X_test, y_test)

0.97

In [67]:
grid.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [68]:
model = grid.best_estimator_

In [69]:
model.score(X_test, y_test)

0.97

In [70]:
import pickle

with open('fishmodel.pkl', 'wb') as f:  #write binary formatında => wb
    pickle.dump(model, f)

with open('fishmodel.pkl', 'rb') as f:  #read binary formatında => rb
    rf = pickle.load(f)    


In [71]:
rf.score(X_test, y_test)

0.97

In [72]:
df.to_csv("C:/Users/DELL/Desktop/veri bilimi kampı/cleaned_fish.csv")