In [102]:
import numpy as np
import pandas as pd

In [103]:
data = pd.read_csv('C:/Users/DELL/Desktop/veri bilimi kampı/CarPrice_Assignment.csv')
df = data.copy()
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [105]:
df.describe().T

count          mean          std      min      25%  \
car_ID            205.0    103.000000    59.322565     1.00    52.00   
symboling         205.0      0.834146     1.245307    -2.00     0.00   
wheelbase         205.0     98.756585     6.021776    86.60    94.50   
carlength         205.0    174.049268    12.337289   141.10   166.30   
carwidth          205.0     65.907805     2.145204    60.30    64.10   
carheight         205.0     53.724878     2.443522    47.80    52.00   
curbweight        205.0   2555.565854   520.680204  1488.00  2145.00   
enginesize        205.0    126.907317    41.642693    61.00    97.00   
boreratio         205.0      3.329756     0.270844     2.54     3.15   
stroke            205.0      3.255415     0.313597     2.07     3.11   
compressionratio  205.0     10.142537     3.972040     7.00     8.60   
horsepower        205.0    104.117073    39.544167    48.00    70.00   
peakrpm           205.0   5125.121951   476.985643  4150.00  4800.00   
citympg           205.0     25.219512     6.542142    13.00    19.00   
highwaympg        205.0     30.751220     6.886443    16.00    25.00   
price             205.0  13276.710571  7988.852332  5118.00  7788.00   

                       50%       75%       max  
car_ID              103.00    154.00    205.00  
symboling             1.00      2.00      3.00  
wheelbase            97.00    102.40    120.90  
carlength           173.20    183.10    208.10  
carwidth             65.50     66.90     72.30  
carheight            54.10     55.50     59.80  
curbweight         2414.00   2935.00   4066.00  
enginesize          120.00    141.00    326.00  
boreratio             3.31      3.58      3.94  
stroke                3.29      3.41      4.17  
compressionratio      9.00      9.40     23.00  
horsepower           95.00    116.00    288.00  
peakrpm            5200.00   5500.00   6600.00  
citympg              24.00     30.00     49.00  
highwaympg           30.00     34.00     54.00  
price             10295.00  16503.00  45400.00

In [106]:
df.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [107]:
df.sample(10)

car_ID  symboling                         CarName fueltype aspiration  \
112     113          0                   peugeot 604sl   diesel      turbo   
121     122          1  plymouth satellite custom (sw)      gas        std   
175     176         -1                   toyota corona      gas        std   
39       40          0                   honda prelude      gas        std   
144     145          0                       subaru r1      gas        std   
186     187          2             volkswagen 411 (sw)      gas        std   
49       50          0                       jaguar xk      gas        std   
202     203         -1                     volvo 244dl      gas        std   
116     117          0                     peugeot 504   diesel      turbo   
5         6          2                        audi fox      gas        std   

    doornumber    carbody drivewheel enginelocation  wheelbase  ...  \
112       four      sedan        rwd          front      107.9  ...   
121       four      sedan        fwd          front       93.7  ...   
175       four  hatchback        fwd          front      102.4  ...   
39        four      sedan        fwd          front       96.5  ...   
144       four      sedan        4wd          front       97.0  ...   
186       four      sedan        fwd          front       97.3  ...   
49         two      sedan        rwd          front      102.0  ...   
202       four      sedan        rwd          front      109.1  ...   
116       four      sedan        rwd          front      107.9  ...   
5          two      sedan        fwd          front       99.8  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
112         152         idi       3.70    3.52             21.0         95   
121          90        2bbl       2.97    3.23              9.4         68   
175         122        mpfi       3.31    3.54              8.7         92   
39          110        1bbl       3.15    3.58              9.0         86   
144         108        2bbl       3.62    2.64              9.0         82   
186         109        mpfi       3.19    3.40              9.0         85   
49          326        mpfi       3.54    2.76             11.5        262   
202         173        mpfi       3.58    2.87              8.8        134   
116         152         idi       3.70    3.52             21.0         95   
5           136        mpfi       3.19    3.40              8.5        110   

     peakrpm citympg  highwaympg    price  
112     4150      28          33  16900.0  
121     5500      31          38   6692.0  
175     4200      27          32   9988.0  
39      5800      27          33   8845.0  
144     4800      24          25   9233.0  
186     5250      27          34   8495.0  
49      5000      13          17  36000.0  
202     5500      18          23  21485.0  
116     4150      28          33  17950.0  
5       5500      19          25  15250.0  

[10 rows x 26 columns]

In [108]:
df.drop(['CarName','car_ID'], axis=1, inplace=True)

In [109]:
df.head()

symboling fueltype aspiration doornumber      carbody drivewheel  \
0          3      gas        std        two  convertible        rwd   
1          3      gas        std        two  convertible        rwd   
2          1      gas        std        two    hatchback        rwd   
3          2      gas        std       four        sedan        fwd   
4          2      gas        std       four        sedan        4wd   

  enginelocation  wheelbase  carlength  carwidth  ...  enginesize  fuelsystem  \
0          front       88.6      168.8      64.1  ...         130        mpfi   
1          front       88.6      168.8      64.1  ...         130        mpfi   
2          front       94.5      171.2      65.5  ...         152        mpfi   
3          front       99.8      176.6      66.2  ...         109        mpfi   
4          front       99.4      176.6      66.4  ...         136        mpfi   

  boreratio stroke  compressionratio horsepower  peakrpm  citympg  highwaympg  \
0      3.47   2.68               9.0        111     5000       21          27   
1      3.47   2.68               9.0        111     5000       21          27   
2      2.68   3.47               9.0        154     5000       19          26   
3      3.19   3.40              10.0        102     5500       24          30   
4      3.19   3.40               8.0        115     5500       18          22   

     price  
0  13495.0  
1  16500.0  
2  16500.0  
3  13950.0  
4  17450.0  

[5 rows x 24 columns]

In [110]:
print(df.columns)

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')


In [111]:
print(df.dtypes)

symboling             int64
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object


In [112]:
df.symboling, labels=pd.factorize(df['symboling'])

In [113]:
labels

Index([3, 1, 2, 0, -1, -2], dtype='int64')

In [114]:
df.fueltype, labels=pd.factorize(df['fueltype'])
labels

Index(['gas', 'diesel'], dtype='object')

In [115]:
df.aspiration, labels=pd.factorize(df['aspiration'])
labels

Index(['std', 'turbo'], dtype='object')

In [116]:
df.doornumber, labels=pd.factorize(df['doornumber'])
labels

Index(['two', 'four'], dtype='object')

In [117]:
 df.carbody, labels=pd.factorize(df['carbody'])
labels

Index(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'], dtype='object')

In [118]:
 df.drivewheel, labels=pd.factorize(df['drivewheel'])
labels 

Index(['rwd', 'fwd', '4wd'], dtype='object')

In [119]:
 df.enginelocation,  labels=pd.factorize(df['enginelocation'])
labels

Index(['front', 'rear'], dtype='object')

In [120]:
df.enginetype,  labels=pd.factorize(df['enginetype'])
labels

Index(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype='object')

In [121]:
df.cylindernumber,  labels=pd.factorize(df['cylindernumber'])
labels

Index(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'], dtype='object')

In [122]:
df.fuelsystem,  labels=pd.factorize(df['fuelsystem'])
labels

Index(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'], dtype='object')

In [123]:
from sklearn.neighbors import LocalOutlierFactor
lof = LocalOutlierFactor(n_neighbors=20)

In [124]:
scores = lof.fit_predict(df)
scores

array([ 1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1])

In [144]:
np.where(scores == -1)[0]

array([  8,  12,  13,  14,  67,  74, 125, 202, 203, 204], dtype=int64)

In [145]:
data.loc[np.where(scores==-1)[0]]

car_ID  symboling                          CarName fueltype aspiration  \
8         9          1                        audi 4000      gas      turbo   
12       13          0                           bmw x1      gas        std   
13       14          0                           bmw x3      gas        std   
14       15          1                           bmw z4      gas        std   
67       68         -1         buick electra 225 custom   diesel      turbo   
74       75          1  buick regal sport coupe (turbo)      gas        std   
125     126          3                    porsche macan      gas        std   
202     203         -1                      volvo 244dl      gas        std   
203     204         -1                        volvo 246   diesel      turbo   
204     205         -1                      volvo 264gl      gas      turbo   

    doornumber    carbody drivewheel enginelocation  wheelbase  ...  \
8         four      sedan        fwd          front      105.8  ...   
12         two      sedan        rwd          front      101.2  ...   
13        four      sedan        rwd          front      101.2  ...   
14        four      sedan        rwd          front      103.5  ...   
67        four      sedan        rwd          front      110.0  ...   
74         two    hardtop        rwd          front      112.0  ...   
125        two  hatchback        rwd          front       94.5  ...   
202       four      sedan        rwd          front      109.1  ...   
203       four      sedan        rwd          front      109.1  ...   
204       four      sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
8           131        mpfi       3.13    3.40              8.3        140   
12          164        mpfi       3.31    3.19              9.0        121   
13          164        mpfi       3.31    3.19              9.0        121   
14          164        mpfi       3.31    3.19              9.0        121   
67          183         idi       3.58    3.64             21.5        123   
74          304        mpfi       3.80    3.35              8.0        184   
125         151        mpfi       3.94    3.11              9.5        143   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
8       5500      17          20  23875.0  
12      4250      21          28  20970.0  
13      4250      21          28  21105.0  
14      4250      20          25  24565.0  
67      4350      22          25  25552.0  
74      4500      14          16  45400.0  
125     5500      19          27  22018.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[10 rows x 26 columns]

In [146]:
#burada araba fiyatları gerçekten de ortalamanın üzerinde bir değer olabilir o yüzden aykırı değerleri silmeyeceğiz
aykırı_index = np.where(scores == -1)[0]
a = list(aykırı_index)
a.remove(67)
a.remove(74)
a.remove(125)

In [147]:
data.drop(a, axis=0, inplace=True)

In [172]:
from sklearn.feature_selection import SelectKBest,f_regression

x=df.drop("price",axis=1)
y=df["price"]

cls = SelectKBest(score_func=f_regression,k=10)
cls.fit(x,y)

SelectKBest(score_func=<function f_regression at 0x00000181BAB3FCE0>)

In [174]:
cls.fit(x,y)

SelectKBest(score_func=<function f_regression at 0x00000181BAB3FCE0>)

In [175]:
cls.scores_

array([2.62958075e+00, 1.77070905e+00, 5.30993687e+00, 1.75527391e-01,
       2.49243645e+00, 8.82093973e+01, 2.91440466e+01, 8.05958249e+01,
       1.53091340e+02, 2.40504973e+02, 1.42796477e+00, 4.25844309e+02,
       7.77383587e-01, 8.66971101e+01, 5.70335877e+02, 2.91393832e+00,
       8.73880985e+01, 1.23167277e+00, 5.97617657e-01, 3.82762007e+02,
       1.87062129e-01, 1.63253455e+02, 1.66203780e+02])

In [176]:
cls.get_support(indices=True)

array([ 5,  8,  9, 11, 13, 14, 16, 19, 21, 22], dtype=int64)

In [180]:
X = df.drop('price',axis=1)
y = df['price']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [181]:
X.columns[cls.get_support(indices=True)]  #en iyi columns

Index(['drivewheel', 'carlength', 'carwidth', 'curbweight', 'cylindernumber',
       'enginesize', 'boreratio', 'horsepower', 'citympg', 'highwaympg'],
      dtype='object')

In [182]:
X.columns

Index(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize',
       'fuelsystem', 'boreratio', 'stroke', 'compressionratio', 'horsepower',
       'peakrpm', 'citympg', 'highwaympg'],
      dtype='object')

In [183]:
X.drop(['symboling', 'fueltype', 'aspiration', 'doornumber', 'carbody','enginelocation', 'wheelbase',
       'carheight', 'enginetype', 'fuelsystem', 'stroke', 'compressionratio', 'peakrpm'], axis=1, inplace=True)

In [184]:
X.describe().T

count         mean         std      min      25%      50%  \
drivewheel      195.0     0.702564    0.550299     0.00     0.00     1.00   
carlength       195.0   173.432821   12.182925   141.10   166.30   172.60   
carwidth        195.0    65.773846    2.046743    60.30    64.00    65.40   
curbweight      195.0  2528.082051  514.449073  1488.00  2134.00  2403.00   
cylindernumber  195.0     0.451282    1.210536     0.00     0.00     0.00   
enginesize      195.0   124.594872   40.027889    61.00    97.00   110.00   
boreratio       195.0     3.322308    0.267569     2.54     3.15     3.31   
horsepower      195.0   102.753846   39.796790    48.00    70.00    94.00   
citympg         195.0    25.502564    6.548294    13.00    19.00    25.00   
highwaympg      195.0    31.076923    6.855597    16.00    25.00    31.00   

                    75%      max  
drivewheel         1.00     2.00  
carlength        180.20   208.10  
carwidth          66.50    72.30  
curbweight      2878.50  4066.00  
cylindernumber     0.00     6.00  
enginesize       140.50   326.00  
boreratio          3.58     3.94  
horsepower       116.00   288.00  
citympg           30.50    49.00  
highwaympg        36.50    54.00

In [185]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [186]:
X = scale.fit_transform(X.values)
X

array([[-1.2799826 , -0.38125044, -0.8199146 , ...,  0.20773986,
        -0.68936338, -0.59621609],
       [-1.2799826 , -0.38125044, -0.8199146 , ...,  0.20773986,
        -0.68936338, -0.59621609],
       [-1.2799826 , -0.18374634, -0.13414044, ...,  1.29101021,
        -0.99557262, -0.74245777],
       ...,
       [-1.2799826 ,  1.26461706,  0.69858532, ...,  1.49254889,
        -1.30178187, -1.3274245 ],
       [-1.2799826 ,  1.26461706,  1.53131109, ...,  0.28331686,
        -0.38315413, -0.44997441],
       [-1.2799826 ,  1.26461706,  1.48232722, ...,  1.44216422,
        -0.99557262, -0.88869946]])

In [193]:
x=pd.DataFrame(X)
x

0         1         2         3         4         5         6  \
0   -1.279983 -0.381250 -0.819915  0.038817 -0.373755  0.135382  0.553399   
1   -1.279983 -0.381250 -0.819915  0.038817 -0.373755  0.135382  0.553399   
2   -1.279983 -0.183746 -0.134140  0.574745  0.454452  0.686413 -2.406711   
3    0.541890  0.260638  0.208747 -0.372387 -0.373755 -0.390603 -0.495754   
4    2.363763  0.260638  0.306714  0.576694  1.282658  0.285663 -0.495754   
..        ...       ...       ...       ...       ...       ...       ...   
190 -1.279983  1.264617  0.698585  1.001539 -0.373755  0.410897  1.714962   
191 -1.279983  1.264617  0.698585  1.007385 -0.373755  0.135382  1.115446   
192 -1.279983  1.264617  0.698585  1.225654 -0.373755  0.135382  1.115446   
193 -1.279983  1.264617  1.531311  0.826144 -0.373755  0.410897  1.714962   
194 -1.279983  1.264617  1.482327  1.015181 -0.373755  0.410897  1.714962   

            7         8         9  
0    0.207740 -0.689363 -0.596216  
1    0.207740 -0.689363 -0.596216  
2    1.291010 -0.995573 -0.742458  
3   -0.018991 -0.230050 -0.157491  
4    0.308509 -1.148677 -1.327425  
..        ...       ...       ...  
190  0.283317 -0.230050 -0.449974  
191  1.492549 -1.301782 -1.327425  
192  1.492549 -1.301782 -1.327425  
193  0.283317 -0.383154 -0.449974  
194  1.442164 -0.995573 -0.888699  

[195 rows x 10 columns]

In [195]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
models ={'RF': RandomForestClassifier(), 'GB':GradientBoostingClassifier(), 'svc':SVC(), 'XGB':xgb.XGBClassifier()}

In [ ]:
# kategorik veri çevriminden sonra mode ile doldur eksik verileri