In [80]:
import numpy as np
import pandas as pd

In [81]:
data = pd.read_csv('C:/Users/DELL/Desktop/veri bilimi kampı/fish.csv')
df = data.copy()
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [83]:
df.describe().T

count        mean         std     min        25%       50%       75%  \
Weight   159.0  398.326415  357.978317  0.0000  120.00000  273.0000  650.0000   
Length1  159.0   26.247170    9.996441  7.5000   19.05000   25.2000   32.7000   
Length2  159.0   28.415723   10.716328  8.4000   21.00000   27.3000   35.5000   
Length3  159.0   31.227044   11.610246  8.8000   23.15000   29.4000   39.6500   
Height   159.0    8.970994    4.286208  1.7284    5.94480    7.7860   12.3659   
Width    159.0    4.417486    1.685804  1.0476    3.38565    4.2485    5.5845   

              max  
Weight   1650.000  
Length1    59.000  
Length2    63.400  
Length3    68.000  
Height     18.957  
Width       8.142

In [84]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [85]:
df.Species,labels=pd.factorize(df["Species"])

In [86]:
from sklearn.neighbors import LocalOutlierFactor

In [87]:
df.sample(10)

Species  Weight  Length1  Length2  Length3   Height   Width
52         1   290.0     24.0     26.0     29.2   8.8768  4.4968
148        6     9.7     10.4     11.0     12.0   2.1960  1.3800
138        5   567.0     43.2     46.0     48.7   7.7920  4.8700
15         0   600.0     29.4     32.0     37.2  15.4380  5.5800
34         0   950.0     38.0     41.0     46.5  17.6235  6.3705
140        5   950.0     48.3     51.7     55.1   8.9262  6.1712
26         0   720.0     32.0     35.0     40.6  16.3618  6.0900
92         4   150.0     20.5     22.5     24.0   6.7920  3.6240
89         4   135.0     20.0     22.0     23.5   5.8750  3.5250
68         3   145.0     19.8     21.5     24.1   9.7364  3.1571

In [88]:
labels

Index(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'], dtype='object')

In [89]:
lof = LocalOutlierFactor(n_neighbors = 20)

In [90]:
scores = lof.fit_predict(df)
scores

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1])

In [91]:
np.where(scores == -1)[0]

array([141, 142, 143, 144], dtype=int64)

In [92]:
df.drop(np.where(scores == -1)[0], axis=0, inplace=True)

In [93]:
data.loc[np.where(scores==-1)[0]] #aykırı veriler

Species  Weight  Length1  Length2  Length3   Height   Width
141    Pike  1250.0     52.0     56.0     59.7  10.6863  6.9849
142    Pike  1600.0     56.0     60.0     64.0   9.6000  6.1440
143    Pike  1550.0     56.0     60.0     64.0   9.6000  6.1440
144    Pike  1650.0     59.0     63.4     68.0  10.8120  7.4800

In [94]:
data.Species.value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [95]:
from sklearn.feature_selection import SelectKBest,f_classif

x=df.drop("Species",axis=1)
y=df["Species"]

cls = SelectKBest(score_func=f_classif,k=4)
cls.fit(x,y)

SelectKBest(k=4)

In [96]:
X = df.drop('Species',axis=1)
y = df['Species']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [97]:
cls.fit(x,y)

SelectKBest(k=4)

In [98]:
cls.scores_

array([15.09997679, 31.66392999, 33.43958725, 37.78538821, 81.48004906,
       23.5148527 ])

In [99]:
cls.get_support(indices=True)

array([1, 2, 3, 4], dtype=int64)

In [100]:
X.columns[cls.get_support(indices=True)]

Index(['Length1', 'Length2', 'Length3', 'Height'], dtype='object')

In [101]:
X.columns

Index(['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width'], dtype='object')

In [102]:
X.drop(['Weight','Width'], axis=1, inplace=True)

In [103]:
X.describe().T

count       mean        std     min       25%      50%      75%  \
Length1  155.0  25.485806   8.897865  7.5000  19.00000  25.0000  32.0000   
Length2  155.0  27.604516   9.555969  8.4000  21.00000  26.5000  35.0000   
Length3  155.0  30.383226  10.468442  8.8000  22.95000  29.2000  39.3500   
Height   155.0   8.939934   4.336074  1.7284   5.92695   7.6156  12.3793   

            max  
Length1  48.300  
Length2  51.700  
Length3  55.100  
Height   18.957

In [104]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [105]:
X = scale.fit_transform(X.values)
X

array([[-0.25772653, -0.231443  , -0.03672638,  0.59695242],
       [-0.16752588, -0.13695573,  0.07827542,  0.81906852],
       [-0.17880096, -0.11595856,  0.06869194,  0.79542241],
       [ 0.09180098,  0.14650606,  0.29869555,  0.87691126],
       [ 0.11435114,  0.14650606,  0.34661297,  0.81073917],
       [ 0.14817639,  0.21999616,  0.41369736,  1.07875927],
       [ 0.14817639,  0.21999616,  0.39453039,  1.21228345],
       [ 0.23837703,  0.25149191,  0.44244781,  0.863029  ],
       [ 0.23837703,  0.25149191,  0.45203129,  1.17188608],
       [ 0.33985276,  0.32498201,  0.55744962,  1.22318102],
       [ 0.32857768,  0.35647776,  0.55744962,  1.23155665],
       [ 0.36240292,  0.35647776,  0.55744962,  1.25668353],
       [ 0.40750325,  0.40897069,  0.57661659,  1.11503824],
       [ 0.45260357,  0.46146361,  0.66286794,  1.15059995],
       [ 0.44132849,  0.46146361,  0.65328446,  1.39157279],
       [ 0.44132849,  0.46146361,  0.65328446,  1.50346378],
       [ 0.5540793 ,  0.

In [106]:
X

array([[-0.25772653, -0.231443  , -0.03672638,  0.59695242],
       [-0.16752588, -0.13695573,  0.07827542,  0.81906852],
       [-0.17880096, -0.11595856,  0.06869194,  0.79542241],
       [ 0.09180098,  0.14650606,  0.29869555,  0.87691126],
       [ 0.11435114,  0.14650606,  0.34661297,  0.81073917],
       [ 0.14817639,  0.21999616,  0.41369736,  1.07875927],
       [ 0.14817639,  0.21999616,  0.39453039,  1.21228345],
       [ 0.23837703,  0.25149191,  0.44244781,  0.863029  ],
       [ 0.23837703,  0.25149191,  0.45203129,  1.17188608],
       [ 0.33985276,  0.32498201,  0.55744962,  1.22318102],
       [ 0.32857768,  0.35647776,  0.55744962,  1.23155665],
       [ 0.36240292,  0.35647776,  0.55744962,  1.25668353],
       [ 0.40750325,  0.40897069,  0.57661659,  1.11503824],
       [ 0.45260357,  0.46146361,  0.66286794,  1.15059995],
       [ 0.44132849,  0.46146361,  0.65328446,  1.39157279],
       [ 0.44132849,  0.46146361,  0.65328446,  1.50346378],
       [ 0.5540793 ,  0.

In [107]:
X.rename(columns={})

AttributeError: 'numpy.ndarray' object has no attribute 'rename'

In [108]:
x=pd.DataFrame(X)
x

0         1         2         3
0   -0.257727 -0.231443 -0.036726  0.596952
1   -0.167526 -0.136956  0.078275  0.819069
2   -0.178801 -0.115959  0.068692  0.795422
3    0.091801  0.146506  0.298696  0.876911
4    0.114351  0.146506  0.346613  0.810739
..        ...       ...       ...       ...
150 -1.576911 -1.617256 -1.627585 -1.584783
151 -1.554361 -1.596259 -1.618001 -1.506209
152 -1.509261 -1.533268 -1.589251 -1.541609
153 -1.385235 -1.396786 -1.455082 -1.403758
154 -1.317584 -1.323296 -1.359247 -1.390015

[155 rows x 4 columns]

In [120]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
models ={'RF': RandomForestClassifier(), 'GB':GradientBoostingClassifier(), 'svc':SVC(), 'XGB':xgb.XGBClassifier()}

In [121]:
for modelName, model in models.items():
    model.fit(X_train, y_train)
    accuracy= accuracy_score(y_test, model.predict(X_test))
    print(f"model: {modelName}, 'accuracy':{accuracy}")

model: RF, 'accuracy':0.8064516129032258
model: GB, 'accuracy':0.8387096774193549
model: svc, 'accuracy':0.45161290322580644
model: XGB, 'accuracy':0.7741935483870968


In [122]:
svm = SVC()
param_grid = {'C': [0.1, 1, 10, 100, 1000],
             'gamma':[1, 0.1, 0.01, 0.001, 0.0001],
             'kernel':['rbf']}

grid = GridSearchCV(svm, cv=5, param_grid = param_grid, refit=True, verbose=3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.320 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.375 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.360 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.320 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.375 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.360 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [123]:
grid.score(X_test, y_test)

0.7419354838709677

In [124]:
grid.best_params_

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}

In [125]:
model = grid.best_estimator_

In [126]:
model.score(X_test, y_test)

0.7419354838709677

In [127]:
import pickle

with open('fishmodel.pkl', 'wb') as f:  #write binary formatında => wb
    pickle.dump(model, f)

with open('fishmodel.pkl', 'rb') as f:  #read binary formatında => rb
    rf = pickle.load(f)    


In [129]:
rf.score(X_test, y_test)

0.7419354838709677

In [130]:
df.to_csv("C:/Users/DELL/Desktop/veri bilimi kampı/cleaned_fish.csv")